name: Python Lint & Type Check
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 mypy isort
      - name: Run Black
        run: black --check .
      - name: Run isort
        run: isort --check-only .
      - name: Run Flake8
        run: flake8 .
      - name: Run mypy
        run: mypy .
